name: container

on:
  - pull_request
  - push

jobs:
  build:
    name: "📦 build container"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4

      - name: Build the container
        run: docker build -t envoy-gateway -f distribution/Dockerfile-ubi .

      - name: Run the container
        run: |
          docker run -d --env PGHOST=localhost --name envoy-gateway envoy --version
