apiVersion: v1
kind: Template
metadata:
  name: community-gateway
labels:
  template: community-gateway
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: community-gateway-config
  data:
    # envoy requires the file extension `yaml` (and not `yml`).
    config.yaml: |
      # The administration endpoint uses a Unix socket instead of TCP in order
      # to avoid exposing it outside of the pod. Requests for metrics and
      # probes will go via an HTTP listener that only accepts requests for the
      # /metrics and /ready paths.
      admin:
        access_log_path: /dev/null
        address:
          pipe:
            path: /sockets/admin.socket

      static_resources:

        ### Clusters ###
        clusters:
        # This backend is used to send metrics and probe requests to the admin endpoint.
        - name: admin
          connect_timeout: 1s
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: admin
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: /sockets/admin.socket

        ### Listeners ###
        listeners:
        # The admin listener isn't exposed, and is used only by the service monitor to scrape metrics.
        - name: admin
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 9000
          filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: admin
                route_config:
                  name: admin
                  virtual_hosts:
                  - name: admin
                    domains:
                    - "*"
                    routes:
                    - name: ready
                      match:
                        path: /ready
                      route:
                        cluster: admin
                    - name: metrics
                      match:
                        path: /metrics
                      route:
                        cluster: admin
                        prefix_rewrite: /stats/prometheus
                http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: community-gateway
    name:  community-gateway

  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: community-gateway
    strategy:
      # Update pod 1 at a time
      type: RollingUpdate
      rollingUpdate:
        # Create at most 0 extra pod over .spec.replicas
        maxSurge: 0
        # At all times there should be .spec.replicas - 1 available
        maxUnavailable: 1

    template:
      metadata:
        labels:
          app: community-gateway
      spec:
        serviceAccountName: community-gateway-sa
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: community-gateway
                topologyKey: kubernetes.io/hostname
        containers:
        - name: community-gateway
          image: "${IMAGE_NAME}:${IMAGE_TAG}"
          command:
          - /usr/bin/envoy
          - --config-path
          - /configs/envoy/config.yaml
          ports:
          - name: metrics
            protocol: TCP
            containerPort: 9000
          # TODO add these when adding the ingress cluster & listener
          # - name: ingress
          #   protocol: TCP
          #   containerPort: 10000
          livenessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
          volumeMounts:
          # TODO add these when adding the ingress cluster & listener
          # - name: tls
          #   mountPath: /secrets/tls
          - name: envoy
            mountPath: /configs/envoy
          - name: sockets
            mountPath: /sockets
        volumes:
        # - name: tls
        #   secret:
        #     secretName: tls
        - name: envoy
          configMap:
            name: community-gateway-config
        - name: sockets
          emptyDir:
            medium: Memory

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: community-gateway-sa
    labels:
      app: community-gateway

- kind: Service
  apiVersion: v1
  metadata:
    name: community-gateway-metrics
    labels:
      app: community-gateway
      port: metrics
    annotations:
      description: Exposes and load balances the account manager Envoy metrics
      qontract.recycle: "true"
      qontract.ignore_reconcile_time: "true"
  spec:
    selector:
      app: community-gateway
    ports:
      - port: 9000
        targetPort: 9000
        name: metrics

# TODO add these when adding the ingress cluster & listener
# - kind: Service
#   apiVersion: v1
#   metadata:
#     name: community-gateway-ingress
#     labels:
#       app: community-gateway
#       port: ingress
#     annotations:
#       description: Exposes and load balances the account manager Envoy
#       # this annotation causes the secret to be created in the namespace
#       service.alpha.openshift.io/serving-cert-secret-name: tls
#       qontract.recycle: "true"
#       qontract.ignore_reconcile_time: "true"
#   spec:
#     selector:
#       app: community-gateway
#     ports:
#       - port: 10000
#         targetPort: 10000
#         protocol: TCP

parameters:
- description: community-gateway image name
  name: IMAGE_NAME
  value: quay.io/cloudservices/community-gateway
  required: true
- description: community-gateway tag, will be set by the deployment pipeline
  name: IMAGE_TAG
  required: true
- description: number of pods to spin up, minimum 3
  name: REPLICAS
  value: "3"
  required: true
- name: CPU_REQUEST
  description: CPU request per container
  value: "200m"
- name: CPU_LIMIT
  description: CPU limit per container
  value: "1"
- name: MEMORY_REQUEST
  description: Memory request per container
  value: "128Mi"
- name: MEMORY_LIMIT
  description: Memory limit per container
  value: "512Mi"
