name: tests

on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - main

jobs:
  kube-linter:
    name: "🎀 kube-linter"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: redhat-actions/oc-installer@v1

    - name: Process template
      run: |
        mkdir processed-templates
        oc process -f templates/gateway.yml \
          -p IMAGE_TAG=image_tag \
          --local \
          -o yaml > processed-templates/gateway.yml

    - uses: stackrox/kube-linter-action@v1.0.4
      with:
        directory: processed-templates
        config: templates/.kube-linter-config.yml
        version: v0.6.5
